# Site settings
title: Loke Carlsson
contact: Kontakt
email: lc222ak@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Presentation av Loke Carlsson som är studerande webbprogrammerare vid Linneuniversitetet, Kalmar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Loke_Carlsson
github_username:  LokeCarlsson

# Build settings
markdown: kramdown
